-- Engedny database schema for Supabase (PostgreSQL)
-- Run this once in Supabase: SQL Editor > New query > Run.

create table if not exists services (
  id bigint generated by default as identity primary key,
  name_en text unique,
  name_ar text,
  icon text
);

create table if not exists users (
  id bigint generated by default as identity primary key,
  full_name text,
  email text unique,
  phone text,
  role text check (role in ('customer', 'provider')),
  password_hash text,
  avatar_data text
);

create table if not exists providers (
  id bigint generated by default as identity primary key,
  user_id bigint unique references users(id),
  service_id bigint references services(id),
  location text,
  experience integer,
  price numeric,
  rating numeric,
  review_count integer,
  bio text
);

create table if not exists requests (
  id bigint generated by default as identity primary key,
  customer_id bigint references users(id),
  provider_id bigint references providers(id),
  service_id bigint references services(id),
  description text,
  location text,
  date text,
  time text,
  price numeric,
  status text default 'Pending',
  created_at timestamptz default now()
);

create table if not exists favorites (
  customer_id bigint references users(id),
  provider_id bigint references providers(id),
  primary key (customer_id, provider_id)
);

create table if not exists messages (
  id bigint generated by default as identity primary key,
  sender_id bigint references users(id),
  receiver_id bigint references users(id),
  body text,
  created_at timestamptz default now(),
  is_read integer default 0,
  delivered_at timestamptz,
  read_at timestamptz,
  attachment_name text,
  attachment_mime text,
  attachment_data text,
  attachment_size integer
);

create table if not exists presence (
  user_id bigint primary key references users(id),
  last_seen_at timestamptz not null default now()
);

create table if not exists notifications (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id),
  title text,
  body text,
  is_read integer default 0,
  created_at timestamptz default now(),
  source_user_id bigint references users(id)
);

create table if not exists reviews (
  id bigint generated by default as identity primary key,
  request_id bigint unique references requests(id),
  customer_id bigint references users(id),
  provider_id bigint references providers(id),
  rating integer check (rating between 1 and 5),
  body text,
  created_at timestamptz default now()
);

create table if not exists payments (
  id bigint generated by default as identity primary key,
  request_id bigint references requests(id),
  method text,
  status text default 'Pending'
);

create table if not exists invoices (
  id bigint generated by default as identity primary key,
  request_id bigint unique references requests(id),
  provider_user_id bigint references users(id),
  work_done text not null,
  materials text,
  labor_amount numeric not null default 0,
  materials_amount numeric not null default 0,
  total_amount numeric not null default 0,
  platform_fee numeric not null default 0,
  payment_method text not null default 'Cash',
  payment_status text not null default 'Pending',
  commission_status text not null default 'Pending',
  commission_method text,
  created_at timestamptz default now()
);

create index if not exists providers_service_id_idx on providers(service_id);
create index if not exists requests_customer_id_idx on requests(customer_id);
create index if not exists requests_provider_id_idx on requests(provider_id);
create index if not exists notifications_user_id_created_at_idx on notifications(user_id, created_at desc);
create index if not exists messages_sender_receiver_id_idx on messages(sender_id, receiver_id, id);
create index if not exists messages_receiver_sender_id_idx on messages(receiver_id, sender_id, id);
