const express = require('express');
const path = require('path');
const Database = require('better-sqlite3');
const crypto = require('crypto');

const app = express();
const db = new Database(path.join(__dirname, 'engedny-local.db'));
db.pragma('foreign_keys = ON');
db.exec(`
  CREATE TABLE IF NOT EXISTS services(id INTEGER PRIMARY KEY, name_en TEXT UNIQUE, name_ar TEXT, icon TEXT);
  CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY, full_name TEXT, email TEXT UNIQUE, phone TEXT, role TEXT);
  CREATE TABLE IF NOT EXISTS providers(id INTEGER PRIMARY KEY, user_id INTEGER UNIQUE, service_id INTEGER, location TEXT, experience INTEGER, price REAL, rating REAL, review_count INTEGER, bio TEXT);
  CREATE TABLE IF NOT EXISTS requests(id INTEGER PRIMARY KEY, customer_id INTEGER, provider_id INTEGER, service_id INTEGER, description TEXT, location TEXT, date TEXT, time TEXT, price REAL, status TEXT DEFAULT 'Pending', created_at TEXT);
  CREATE TABLE IF NOT EXISTS favorites(customer_id INTEGER, provider_id INTEGER, PRIMARY KEY(customer_id, provider_id));
  CREATE TABLE IF NOT EXISTS messages(id INTEGER PRIMARY KEY, sender_id INTEGER, receiver_id INTEGER, body TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP, is_read INTEGER DEFAULT 0);
  CREATE TABLE IF NOT EXISTS presence(user_id INTEGER PRIMARY KEY, last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
  CREATE TABLE IF NOT EXISTS notifications(id INTEGER PRIMARY KEY, user_id INTEGER, title TEXT, body TEXT, is_read INTEGER DEFAULT 0, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
  CREATE TABLE IF NOT EXISTS reviews(id INTEGER PRIMARY KEY, request_id INTEGER UNIQUE, customer_id INTEGER, provider_id INTEGER, rating INTEGER, body TEXT, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
  CREATE TABLE IF NOT EXISTS payments(id INTEGER PRIMARY KEY, request_id INTEGER, method TEXT, status TEXT DEFAULT 'Pending');
`);
if (!db.prepare("PRAGMA table_info(users)").all().some(c => c.name === 'password_hash')) db.exec('ALTER TABLE users ADD COLUMN password_hash TEXT');
if (!db.prepare("PRAGMA table_info(users)").all().some(c => c.name === 'avatar_data')) db.exec('ALTER TABLE users ADD COLUMN avatar_data TEXT');
if (!db.prepare("PRAGMA table_info(messages)").all().some(c => c.name === 'delivered_at')) db.exec('ALTER TABLE messages ADD COLUMN delivered_at TEXT');
if (!db.prepare("PRAGMA table_info(messages)").all().some(c => c.name === 'read_at')) db.exec('ALTER TABLE messages ADD COLUMN read_at TEXT');
if (!db.prepare("PRAGMA table_info(messages)").all().some(c => c.name === 'attachment_name')) db.exec('ALTER TABLE messages ADD COLUMN attachment_name TEXT');
if (!db.prepare("PRAGMA table_info(messages)").all().some(c => c.name === 'attachment_mime')) db.exec('ALTER TABLE messages ADD COLUMN attachment_mime TEXT');
if (!db.prepare("PRAGMA table_info(messages)").all().some(c => c.name === 'attachment_data')) db.exec('ALTER TABLE messages ADD COLUMN attachment_data TEXT');
if (!db.prepare("PRAGMA table_info(messages)").all().some(c => c.name === 'attachment_size')) db.exec('ALTER TABLE messages ADD COLUMN attachment_size INTEGER');
if (!db.prepare("PRAGMA table_info(notifications)").all().some(c => c.name === 'source_user_id')) db.exec('ALTER TABLE notifications ADD COLUMN source_user_id INTEGER');
const hashPassword = password => { const salt = crypto.randomBytes(16).toString('hex'); return `${salt}:${crypto.scryptSync(password, salt, 64).toString('hex')}`; };
const passwordMatches = (password, stored='') => { const [salt, key] = stored.split(':'); return !!salt && crypto.timingSafeEqual(Buffer.from(key,'hex'), crypto.scryptSync(password,salt,64)); };
const publicUser = user => { const { password_hash, ...safe } = user; return safe; };

function seed() {
  if (db.prepare('SELECT count(*) n FROM services').get().n) return;
  const service = db.prepare('INSERT INTO services(name_en,name_ar,icon) VALUES(?,?,?)');
  [['Electrician','كهربائي','⚡'],['Plumber','سباك','🔧'],['Carpenter','نجار','🪚'],['Painter','دهان','🎨'],['AC Technician','فني تكييف','❄'],['Cleaning','تنظيف','✦'],['Appliance Repair','إصلاح أجهزة','🛠'],['General Maintenance','صيانة عامة','🏠'],['Gardening','بستنة','🌿'],['Pest Control','مكافحة حشرات','🪲'],['Moving','نقل أثاث','🚚'],['Home Internet','إنترنت منزلي','📶']].forEach(x=>service.run(...x));
  db.prepare("INSERT INTO users(id,full_name,email,phone,role,password_hash) VALUES(1,'أحمد السيد','customer@engedny.local','01000000000','customer',?)").run(hashPassword('Demo1234'));
  const user = db.prepare('INSERT INTO users(full_name,email,phone,role) VALUES(?,?,?,?)');
  const provider = db.prepare('INSERT INTO providers(user_id,service_id,location,experience,price,rating,review_count,bio) VALUES(?,?,?,?,?,?,?,?)');
  [['محمد علي','mohamed@engedny.local','01010000001',2,'القاهرة',8,200,4.9,41,'كهربائي مرخّص للاستجابات السريعة.'],['أحمد محمود','ahmedp@engedny.local','01010000002',1,'الجيزة',6,150,4.8,24,'متخصص سباكة للمنازل والمكاتب.'],['سارة محمود','sara@engedny.local','01010000003',6,'الجيزة',4,120,4.7,18,'تنظيف احترافي دقيق وودود.'],['عمر عادل','omar@engedny.local','01010000004',5,'القاهرة',7,220,4.6,29,'تركيب وصيانة أجهزة التكييف.']].forEach(([name,email,phone,serviceId,location,experience,price,rating,reviews,bio])=>{const id=user.run(name,email,phone,'provider').lastInsertRowid;provider.run(id,serviceId,location,experience,price,rating,reviews,bio);});
}
seed();
const addService = db.prepare('INSERT OR IGNORE INTO services(name_en,name_ar,icon) VALUES(?,?,?)');
[['Gardening','بستنة','🌿'],['Pest Control','مكافحة حشرات','🪲'],['Moving','نقل أثاث','🚚'],['Home Internet','إنترنت منزلي','📶']].forEach(x=>addService.run(...x));
db.prepare("UPDATE users SET password_hash=? WHERE id=1 AND (password_hash IS NULL OR password_hash='')").run(hashPassword('Demo1234'));
db.prepare("UPDATE users SET password_hash=? WHERE role='provider' AND (password_hash IS NULL OR password_hash='')").run(hashPassword('Demo1234'));
function providerSearch(term='') { const q=`%${term}%`; return db.prepare(`SELECT p.*,u.full_name,u.phone,u.avatar_data,s.name_en,s.name_ar,s.icon FROM providers p JOIN users u ON u.id=p.user_id JOIN services s ON s.id=p.service_id WHERE lower(u.full_name) LIKE lower(?) OR lower(s.name_en) LIKE lower(?) OR s.name_ar LIKE ? OR lower(p.location) LIKE lower(?) ORDER BY p.rating DESC`).all(q,q,q,q); }
function appData() { return { user:db.prepare('SELECT * FROM users WHERE id=1').get(), services:db.prepare('SELECT * FROM services').all(), providers:providerSearch(), requests:db.prepare(`SELECT r.*,s.name_ar,u.full_name provider_name FROM requests r JOIN services s ON s.id=r.service_id JOIN providers p ON p.id=r.provider_id JOIN users u ON u.id=p.user_id WHERE r.customer_id=1 ORDER BY r.id DESC`).all() }; }

app.use(express.json({limit:'7mb'}));
app.use((_, res, next) => { res.set('Cache-Control', 'no-store'); next(); });
app.get('/api/services',(_,res)=>res.json(db.prepare('SELECT * FROM services').all()));
app.get('/api/users',(req,res)=>{const role=req.query.role;const rows=role?db.prepare('SELECT * FROM users WHERE role=? ORDER BY full_name').all(role):db.prepare('SELECT * FROM users ORDER BY full_name').all();res.json(rows.map(publicUser));});
app.get('/api/chat-peers/:userId',(req,res)=>{const userId=Number(req.params.userId),user=db.prepare('SELECT id,role FROM users WHERE id=?').get(userId);if(!user)return res.status(404).json({error:'المستخدم غير موجود'});const peers=user.role==='provider'?db.prepare("SELECT id,full_name,avatar_data,'customer' AS role FROM users WHERE role='customer' AND id<>? ORDER BY full_name").all(userId):db.prepare("SELECT u.id,u.full_name,u.avatar_data,'provider' AS role,p.location,s.name_ar,s.name_en FROM users u JOIN providers p ON p.user_id=u.id JOIN services s ON s.id=p.service_id WHERE u.role='provider' AND u.id<>? ORDER BY u.full_name").all(userId);res.json(peers.map(publicUser));});
app.post('/api/auth/login',(req,res)=>{const {email,password}=req.body||{};const user=db.prepare('SELECT * FROM users WHERE lower(email)=lower(?)').get(String(email||'').trim());if(!user||!passwordMatches(password,user.password_hash))return res.status(401).json({error:'البريد الإلكتروني أو كلمة المرور غير صحيحة.'});res.json({user:publicUser(user)});});
app.post('/api/auth/signup',(req,res)=>{const r=req.body||{};if(!r.fullName?.trim()||!r.email?.trim()||!r.phone?.trim()||!r.password||!['customer','provider'].includes(r.role))return res.status(400).json({error:'أكمل البيانات المطلوبة.'});if(r.password!==r.confirmPassword)return res.status(400).json({error:'تأكيد كلمة المرور غير مطابق.'});if(r.password.length<8)return res.status(400).json({error:'كلمة المرور يجب أن تكون 8 أحرف على الأقل.'});if(r.avatarData&&(!/^data:image\/(png|jpeg|webp);base64,/.test(r.avatarData)||r.avatarData.length>2000000))return res.status(400).json({error:'الصورة يجب أن تكون PNG أو JPG أو WEBP وأصغر من 1.5MB.'});if(db.prepare('SELECT 1 FROM users WHERE lower(email)=lower(?)').get(r.email.trim()))return res.status(409).json({error:'هذا البريد مستخدم بالفعل.'});const id=db.prepare('INSERT INTO users(full_name,email,phone,role,password_hash,avatar_data) VALUES(?,?,?,?,?,?)').run(r.fullName.trim(),r.email.trim().toLowerCase(),r.phone.trim(),r.role,hashPassword(r.password),r.avatarData||null).lastInsertRowid;if(r.role==='provider'){if(!r.serviceId)return res.status(400).json({error:'اختر الخدمة التي تقدمها.'});db.prepare('INSERT INTO providers(user_id,service_id,location,experience,price,rating,review_count,bio) VALUES(?,?,?,?,?,?,?,?)').run(id,r.serviceId,r.location?.trim()||'غير محدد',Number(r.experience)||0,Number(r.price)||0,0,0,r.bio?.trim()||'');}res.status(201).json({user:publicUser(db.prepare('SELECT * FROM users WHERE id=?').get(id))});});
app.patch('/api/users/:id/avatar',(req,res)=>{const id=Number(req.params.id),avatarData=req.body?.avatarData;if(!/^data:image\/(png|jpeg|webp);base64,/.test(avatarData||'')||avatarData.length>2000000)return res.status(400).json({error:'اختر PNG أو JPG أو WEBP أقل من 1.5MB.'});if(!db.prepare('SELECT 1 FROM users WHERE id=?').get(id))return res.status(404).end();db.prepare('UPDATE users SET avatar_data=? WHERE id=?').run(avatarData,id);res.json({user:publicUser(db.prepare('SELECT * FROM users WHERE id=?').get(id))});});
app.get('/api/data',(req,res)=>{const userId=Number(req.query.userId)||1;const user=db.prepare('SELECT * FROM users WHERE id=?').get(userId);if(!user)return res.status(404).json({error:'المستخدم غير موجود'});if(user.role==='provider'){const p=db.prepare('SELECT * FROM providers WHERE user_id=?').get(userId);return res.json({user:publicUser(user),profile:p,services:db.prepare('SELECT * FROM services').all(),providers:providerSearch(),favoriteCustomers:db.prepare('SELECT u.id,u.full_name,u.avatar_data FROM favorites f JOIN users u ON u.id=f.customer_id WHERE f.provider_id=? ORDER BY u.full_name').all(p.id),requests:db.prepare(`SELECT r.*,s.name_ar,s.name_en,u.full_name customer_name,u.id customer_user_id FROM requests r JOIN services s ON s.id=r.service_id JOIN users u ON u.id=r.customer_id WHERE r.provider_id=? ORDER BY r.id DESC`).all(p.id)});}res.json({user:publicUser(user),services:db.prepare('SELECT * FROM services').all(),providers:providerSearch(),favorites:db.prepare('SELECT provider_id FROM favorites WHERE customer_id=?').all(userId).map(x=>x.provider_id),requests:db.prepare(`SELECT r.*,s.name_ar,s.name_en,u.full_name provider_name,u.id provider_user_id,pay.id payment_id,pay.method payment_method,pay.status payment_status FROM requests r JOIN services s ON s.id=r.service_id JOIN providers p ON p.id=r.provider_id JOIN users u ON u.id=p.user_id LEFT JOIN payments pay ON pay.request_id=r.id WHERE r.customer_id=? ORDER BY r.id DESC`).all(userId)});});
app.get('/api/providers',(req,res)=>res.json(providerSearch(req.query.q||'')));
app.post('/api/requests',(req,res)=>{const r=req.body||{},price=Number.isFinite(Number(r.price))?Number(r.price):0,customer=db.prepare("SELECT id FROM users WHERE id=? AND role='customer'").get(Number(r.userId)),provider=db.prepare('SELECT user_id FROM providers WHERE id=?').get(Number(r.providerId));if(!customer||!provider||!r.serviceId||!r.description?.trim()||!r.location?.trim()||!r.date||!r.time||price<0)return res.status(400).json({error:'بيانات الطلب غير مكتملة أو مقدم الخدمة غير متاح.'});const id=db.prepare("INSERT INTO requests(customer_id,provider_id,service_id,description,location,date,time,price,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,datetime('now'))").run(customer.id,Number(r.providerId),Number(r.serviceId),r.description.trim(),r.location.trim(),r.date,r.time,price,'Pending').lastInsertRowid;db.prepare('INSERT INTO notifications(user_id,title,body) VALUES(?,?,?)').run(provider.user_id,'طلب خدمة جديد','لديك طلب جديد يحتاج إلى ردك.');res.status(201).json({id});});
app.post('/api/favorites/:id',(req,res)=>{const id=Number(req.params.id),customerId=Number(req.body?.userId);if(!customerId)return res.status(400).json({error:'المستخدم مطلوب'});const found=db.prepare('SELECT 1 FROM favorites WHERE customer_id=? AND provider_id=?').get(customerId,id);if(found)db.prepare('DELETE FROM favorites WHERE customer_id=? AND provider_id=?').run(customerId,id);else db.prepare('INSERT INTO favorites(customer_id,provider_id) VALUES(?,?)').run(customerId,id);res.json({favorite:!found});});
app.patch('/api/requests/:id/status',(req,res)=>{const id=Number(req.params.id),status=req.body?.status;if(!['Pending','Accepted','On the way','In Progress','Completed','Rejected','Cancelled'].includes(status))return res.status(400).json({error:'Invalid status'});const r=db.prepare('SELECT * FROM requests WHERE id=?').get(id);if(!r)return res.status(404).end();db.prepare('UPDATE requests SET status=? WHERE id=?').run(status,id);db.prepare('INSERT INTO notifications(user_id,title,body) VALUES(?,?,?)').run(r.customer_id,'تحديث الطلب',`تم تحديث حالة طلبك إلى ${status}`);res.json({status});});
app.get('/api/notifications/:userId',(req,res)=>res.json(db.prepare('SELECT * FROM notifications WHERE user_id=? ORDER BY id DESC').all(Number(req.params.userId))));
app.post('/api/presence',(req,res)=>{const userId=Number(req.body?.userId);if(!db.prepare('SELECT 1 FROM users WHERE id=?').get(userId))return res.status(404).json({error:'الحساب غير موجود.'});db.prepare("INSERT INTO presence(user_id,last_seen_at) VALUES(?,datetime('now')) ON CONFLICT(user_id) DO UPDATE SET last_seen_at=datetime('now')").run(userId);db.prepare("UPDATE messages SET delivered_at=COALESCE(delivered_at,datetime('now')) WHERE receiver_id=? AND delivered_at IS NULL").run(userId);res.json({ok:true});});
app.get('/api/messages/:a/:b',(req,res)=>{const a=Number(req.params.a),b=Number(req.params.b);if(req.query.markRead!=='0')db.prepare("UPDATE messages SET delivered_at=COALESCE(delivered_at,datetime('now')),read_at=COALESCE(read_at,datetime('now')),is_read=1 WHERE sender_id=? AND receiver_id=?").run(b,a);res.json(db.prepare('SELECT * FROM messages WHERE (sender_id=? AND receiver_id=?) OR (sender_id=? AND receiver_id=?) ORDER BY id').all(a,b,b,a));});
app.post('/api/messages',(req,res)=>{const r=req.body||{},senderId=Number(r.senderId),receiverId=Number(r.receiverId),message=String(r.body||'').trim(),attachment=r.attachment||null;if(!senderId||!receiverId||senderId===receiverId||(!message&&!attachment))return res.status(400).json({error:'اكتب رسالة أو أضف ملفًا.'});let fileName=null,fileMime=null,fileData=null,fileSize=null;if(attachment){fileName=String(attachment.name||'').trim().slice(0,160);fileMime=String(attachment.mime||'application/octet-stream').trim().toLowerCase();fileData=String(attachment.data||'');fileSize=Number(attachment.size)||0;const dataMatch=/^data:([^;,]+);base64,[A-Za-z0-9+/=]+$/.exec(fileData);if(!fileName||!dataMatch||dataMatch[1].toLowerCase()!==fileMime||fileMime.startsWith('video/')||fileSize<1||fileSize>4000000||fileData.length>5400000)return res.status(400).json({error:'الملف غير صالح. الفيديو غير مسموح والحد الأقصى 4MB.'});}const sender=db.prepare('SELECT full_name FROM users WHERE id=?').get(senderId),receiver=db.prepare('SELECT 1 FROM users WHERE id=?').get(receiverId);if(!sender||!receiver)return res.status(404).json({error:'الحساب غير موجود.'});const online=!!db.prepare("SELECT 1 FROM presence WHERE user_id=? AND last_seen_at>=datetime('now','-12 seconds')").get(receiverId);const id=db.prepare('INSERT INTO messages(sender_id,receiver_id,body,attachment_name,attachment_mime,attachment_data,attachment_size,delivered_at) VALUES(?,?,?,?,?,?,?,?)').run(senderId,receiverId,message,fileName,fileMime,fileData,fileSize,online?new Date().toISOString():null).lastInsertRowid;const noticeBody=message||`أرسل ملفًا: ${fileName}`;db.prepare('INSERT INTO notifications(user_id,title,body,source_user_id) VALUES(?,?,?,?)').run(receiverId,`${sender.full_name} أرسل رسالة`,noticeBody,senderId);res.status(201).json({id,status:online?'delivered':'sent'});});
app.post('/api/reviews',(req,res)=>{const r=req.body;if(!r.requestId||!r.customerId||!r.providerId||r.rating<1||r.rating>5)return res.status(400).end();db.prepare('INSERT INTO reviews(request_id,customer_id,provider_id,rating,body) VALUES(?,?,?,?,?)').run(r.requestId,r.customerId,r.providerId,r.rating,r.body||'');db.prepare('UPDATE providers SET rating=(SELECT AVG(rating) FROM reviews WHERE provider_id=?),review_count=(SELECT COUNT(*) FROM reviews WHERE provider_id=?) WHERE id=?').run(r.providerId,r.providerId,r.providerId);res.status(201).end();});
app.get('/api/payments/:requestId',(req,res)=>res.json(db.prepare('SELECT * FROM payments WHERE request_id=?').all(Number(req.params.requestId))));
app.post('/api/payments',(req,res)=>{const r=req.body||{},requestId=Number(r.requestId),job=db.prepare('SELECT status FROM requests WHERE id=?').get(requestId);if(!requestId||!['Cash','Card','Wallet'].includes(r.method))return res.status(400).json({error:'اختر طريقة دفع صالحة.'});if(!job||job.status!=='Completed')return res.status(400).json({error:'الدفع متاح بعد إتمام الخدمة فقط.'});if(db.prepare('SELECT 1 FROM payments WHERE request_id=?').get(requestId))return res.status(409).json({error:'تم تسجيل الدفع لهذا الطلب بالفعل.'});db.prepare('INSERT INTO payments(request_id,method,status) VALUES(?,?,?)').run(requestId,r.method,r.method==='Cash'?'الدفع عند الاستلام':'تم الدفع');res.status(201).json({ok:true});});
// Serve only the browser assets; never expose the local SQLite database.
app.get('/', (_, res) => res.sendFile(path.join(__dirname, 'index.html')));
app.get('/styles.css', (_, res) => res.sendFile(path.join(__dirname, 'styles.css')));
app.get('/theme.css', (_, res) => res.sendFile(path.join(__dirname, 'theme.css')));
app.get('/polish.css', (_, res) => res.sendFile(path.join(__dirname, 'polish.css')));
app.get('/profile.css', (_, res) => res.sendFile(path.join(__dirname, 'profile.css')));
app.get('/responsive.css', (_, res) => res.sendFile(path.join(__dirname, 'responsive.css')));
app.get('/rtl.css', (_, res) => res.sendFile(path.join(__dirname, 'rtl.css')));
app.get('/renderer.js', (_, res) => res.sendFile(path.join(__dirname, 'renderer.js')));
app.use('/assets', express.static(path.join(__dirname, 'assets')));
const port=Number(process.env.PORT)||3000;
app.listen(port,()=>console.log(`Engedny is running at http://localhost:${port}`));
